### ISSUE TITLE
what's wrong happened?

### ISSUE THREAD

**Issue by want20** [tagattie/FreeBSD-Atom#1]
cp -f /usr/home/want20/Src/FreeBSD-Atom/editors/atom/work/node-v10.11.0/out/Release/node  /usr/home/want20/Src/FreeBSD-Atom/editors/atom/work/atom/apm/node_modules/atom-package-manager/bin
cd /usr/home/want20/Src/FreeBSD-Atom/editors/atom/work/atom && /usr/bin/env XDG_DATA_HOME=/usr/home/want20/Src/FreeBSD-Atom/editors/atom/work  XDG_CONFIG_HOME=/usr/home/want20/Src/FreeBSD-Atom/editors/atom/work  HOME=/usr/home/want20/Src/FreeBSD-Atom/editors/atom/work PATH=/usr/home/want20/Src/FreeBSD-Atom/editors/atom/work/.bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-isystem /usr/local/include"  LDFLAGS=" -fstack-protector-strong -L/usr/local/lib " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -isystem /usr/local/include "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" ./script/bootstrap-part2	# should now succeed
Node:	v11.13.0
Npm:	v6.2.0
Installing apm
child_process.js:658
    throw err;
    ^

Error: spawnSync /usr/home/want20/Src/FreeBSD-Atom/editors/atom/work/atom/apm/node_modules/atom-package-manager/bin/apm ENOENT
    at Object.spawnSync (internal/child_process.js:1021:20)
    at spawnSync (child_process.js:622:24)
    at Object.execFileSync (child_process.js:650:13)
    at Object.<anonymous> (/usr/home/want20/Src/FreeBSD-Atom/editors/atom/work/atom/script/bootstrap-part2:32:14)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
*** Error code 1

Stop.
make: stopped in /usr/home/want20/Src/FreeBSD-Atom/editors/atom

**Comment by tagattie** [comment]
Thanks for the report. This may be due to insufficient build-time dependency.
Can you install `shells/bash` and try again to see if the problem persists?

**Comment by tagattie** [comment]
Adding `shells/bash` to build-time and runtime dependencies have solved the problem. Closing.
