### ISSUE TITLE
poudriere build fails

### ISSUE THREAD

**Issue by pizzamig** [tagattie/FreeBSD-Atom#3]
I was testing the build on poudriere, to see if I could commit it to the tree.
However, `npm` tries do download stuff during the build phase.
Here is the log: [atom-1.41.0.log](https://github.com/tagattie/FreeBSD-Atom/files/3866032/atom-1.41.0.log)

Probably, the fix is to adopt the same solution adopted for electron4.

**Comment by tagattie** [comment]
The port is not yet compatible with poudriere.

`npm install` has `--offline` option since version 5. I will investigate whether the option can be used to solve the issue.

**Comment by ehaupt** [comment]
The port is now in a good shape and builds fine in poudriere. It should probably be marked " ONLY_FOR_ARCHS=amd64". Other than that I think this would be a good moment to add it to the ports tree. What do you think @tagattie, @pizzamig ?

**Comment by ehaupt** [comment]
Plus, it also needs MAX_FILES_atom=4096 in poudriere.conf. @pizzamig what was the process for vscode to have this implemented on all the build clusters?

**Comment by pizzamig** [comment]
I've just asked antoine@ if it was possible to change it.
for vscode I asked a value of 8192, to be on the safe side for future releases

**Comment by tagattie** [comment]
Hi @ehaupt,

I forgot to update this issue. Thanks for picking this up. I would be happy if you can add this to the ports tree.

**Comment by tagattie** [comment]
Now the port can be built with poudriere. So close this issue.
