### ISSUE TITLE
FreeBSD 13.0 version

### ISSUE THREAD

**Issue by yaazkal** [tagattie/FreeBSD-Atom#8]
Hi, since FreeBSD 13.0-RELEASE is pretty close, I've tried to build this on FreeBSD 13.0-RC5 but since I have no experience building things from ports I didn't know what to do next.

I've tried replacing `python:2.7` for `python` [here](https://github.com/tagattie/FreeBSD-Atom/blob/16a09c4c479e35d9739591ee1620dcabfa5d9d8d/editors/atom/Makefile#L62) and also `electron6` for `electron11` [here](https://github.com/tagattie/FreeBSD-Atom/blob/16a09c4c479e35d9739591ee1620dcabfa5d9d8d/editors/atom/Makefile#L66)

Maybe is not that simple. Anyway after two hours of building I end up with this:

![image](https://user-images.githubusercontent.com/5897701/113642108-b2677800-9644-11eb-9ceb-391cb29d420f.png)

If you can guide me what to do or if you have in your plans making atom available in FreeBSD 13.0 I do appreciate it.

Thanks !

**Comment by yaazkal** [comment]
By the way, this was in my `/etc/make.conf` thanks to a friend

```
# Install dependencies via pkg. -- cwells
USE_PACKAGE_DEPENDS=yes
# Use ccache. -- cwells
WITH_CCACHE_BUILD=yes
CCACHE_DIR=/var/tmp/ccache
# Compile in RAM. -- cwells
WRKDIRPREFIX=/ram
```
Here `/ram` is a mount point in RAM so it compiles faster

**Comment by tagattie** [comment]
Electron 6 is not available as an official port. Try the following repository instead:
https://github.com/tagattie/FreeBSD-Electron

I guess electron 11 is not compatible with the current version of atom.

**Comment by yaazkal** [comment]
Thank you so much.
I was able to compile and install it using electron 6 from your other repo doing the changes I mention in the original post.

I'm not opening a PR since there is no electron 6 in ports.

Have a nice day!

**Comment by tagattie** [comment]
Great to hear that. Closing this.
